### ISSUE TITLE
Update mentions of React Query to TanStack Query

### ISSUE THREAD

**Issue by chimon2000** [KRTirtho/fl-query#12]
React Query was recently renamed TanStack Query since it's now a cross-framework library.

Updating its mentions on the website and in the README will improve SEO in searches on Google and pub.dev.

**Comment by KRTirtho** [comment]
I think people are still not aware of this rename. Maybe adding a something like this `(formerly react-query)` would be better, right?

**Comment by chimon2000** [comment]
> I think people are still not aware of this rename. Maybe adding a something like this `(formerly react-query)` would be better, right?

Yes that probably makes the most sense!

**Comment by KRTirtho** [comment]
Updated the docs :+1:
