### ISSUE TITLE
[Bug] `refetchOnChangeExternalData` doesn't work

### ISSUE THREAD

**Issue by KRTirtho** [KRTirtho/fl-query#18]
`QueryBuilder` and `InfiniteQueryBuilder` refetches when `externalData` has changed but the `setExternalData` method isn't used to set the new instance of `externalData` inside `QueryBowl.fetchQuery` so `QueryJob.task` is run with the old `externalData` instance

References:

- [query_bow.dartl](https://github.com/KRTirtho/fl-query/blob/main/packages/fl_query/lib/src/query_bowl.dart)
- [use_query.dart](https://github.com/KRTirtho/fl-query/blob/main/packages/fl_query_hooks/lib/src/use_query.dart)
- [query_builder.dart](https://github.com/KRTirtho/fl-query/blob/main/packages/fl_query/lib/src/query_builder.dart)

**Comment by Arjun544** [comment]
Hello @KRTirtho, Kindly fix this bug. I want to use this feature

**Comment by KRTirtho** [comment]
@Arjun544 if you need it right now, you can use this commit https://github.com/KRTirtho/fl-query/commit/51cad709543a94229b4c670ef2ff31ad782bc586 for now

**Comment by Arjun544** [comment]
@KRTirtho I have a quick question regarding QueryJob.withVariableKey.
I have a use case in the app where the user has 2 types of profiles( fun & professional ), by default Im fetching details of the "fun" profile, but the user can change the type to professional from the profile page.

Currently, I'm using  QueryJob.withVariableKey for dynamic switching between fun and professional types. Everything is working fine but QueryJob.withVariableKey refetch data on a screen that is not even currently visible.

Is there any way I can refetch the data only when I navigate to the particular screen with QueryJob.withVariableKey?

**Comment by KRTirtho** [comment]
Currently, like React-Query, fl-query doesn't support the glob path `queryKey` matching e.g. `some-query-key*`
Which can be used to `refetch` a group of queries at once

Since you know what are the dynamic params (`fun` / `professional`) are. You can manually do the `refetching` for now. You can do the following in the page where you want to `refetch` those queries

```dart
initState(){
  super.initState();
  WidgetBinding.instance.addPostFrameCallback((_) async {
     final bowl = QueryBowl.of(context);
     await bowl.getQuery(userQuery.withVariableKey("fun"))?.refetch();
     await bowl.getQuery(userQuery.withVariableKey("professional"))?.refetch();
   }
}
````

Or inside zero dependency `useEffect`
```dart
useEffect((){
  WidgetBinding.instance.addPostFrameCallback((_) async {
     final bowl = QueryBowl.of(context);
     await bowl.getQuery(userQuery.withVariableKey("fun"))?.refetch();
     await bowl.getQuery(userQuery.withVariableKey("professional"))?.refetch();
  }
 }, []);
```

**Comment by Arjun544** [comment]
Thank you, I will try to implement this approach.
