### ISSUE TITLE
scheduleToQueue might not be working properly

### ISSUE THREAD

**Issue by PetrKubes97** [KRTirtho/fl-query#34]
After migrating to v1.0.0, I tried to replace:
`await mutateAsync` with `await .....mutate(..., scheduleToQueue: true);`
However, it seems like the future is immediately returned, without waiting for the result. 

I've looked at the code, and my guess is that `_operate` returns immediately after `CancellableRetryOperation` is created. Maybe 
`await _operation.valueOrCancellation();` could be the solution?

**Comment by PetrKubes97** [comment]
I've also notices that final data = awaiting query.refresh() does not work and tested
```
someQuery.refresh();
someQuery.reset();
```
Which does not cancel the job. I assume it should? I can do a PR if it's not the intended behaviour.

**Comment by KRTirtho** [comment]
I guess you got the wrong idea about `scheduleToQueue`. It's intended to complete the future immediately without the operation being successful. It's similar to scheduling any job to a task queue. To wait for the mutation operation to complete, just set it to `false` which is the default btw

**Comment by KRTirtho** [comment]
> I've also notices that final data = awaiting query.refresh() does not work and tested
> 
> ```
> someQuery.refresh();
> someQuery.reset();
> ```
> 
> Which does not cancel the job. I assume it should? I can do a PR if it's not the intended behaviour.

`query.refresh` is supposed to refresh/refetch the query. It doesn't cancel any running job.
`query.reset` resets the state of the query and tries to cancel the operation

**Comment by PetrKubes97** [comment]
Hi, this:
> To wait for the mutation operation to complete, just set it to false which is the default btw
does not seem to work. I've made a PR to my fork (I wanted the other fix as well) but if it makes sense, I can make to this repo as well. 

Congrats on the Spotube HN post btw 🎉 

https://github.com/PetrKubes97/fl-query/pull/1/files

**Comment by KRTirtho** [comment]
I guess I missed something there. My guess is the mutex for some reason loses the context it is working in thus never returning the value. So maybe it's creating zombie results. I'll check it tomorrow. 

Sorry for inactivity. I took a break for some while 😄
