### ISSUE TITLE
staleQueries cause infinite loop

### ISSUE THREAD

**Issue by PetrKubes97** [KRTirtho/fl-query#37]
This one caused me some trouble (crashing server 😅) luckily my app does not have too many users yet. 

I think the way to reproduce this is to set QueryClient(staleDuration: const Duration(seconds: 1)) and then going back and forth from the screen with the query. I think the query key also needs to be refetch from another screen. 

Then, fl_query starts firing requests on every millisecond, which is a lot. :D 

My temporary fix rn is just `QueryClient(staleDuration: const Duration(days: 9999))`

**Comment by ganeshh123** [comment]
Same issue here :(
