### ISSUE TITLE
usequery with params

### ISSUE THREAD

**Issue by affansk** [KRTirtho/fl-query#41]
Hi @KRTirtho  is there a way we can call query with params.

query.refresh or query.fetch({offset,limit, name})

**final query =
    useQuery<dynamic, Exception>(
  "listofmanufacturer",
  ({offset, limit, name}) async {
    return await getListOfVehicleBrand(offset,limit, name);
  },
  enabled: false,
  retryConfig: RetryConfig(
      maxRetries: 1,
      retryDelay: Duration(microseconds: 2000),
      cancelWhenOffline: true),
);**

**Comment by affansk** [comment]
@KRTirtho would you mind something telling on this ?

**Comment by KRTirtho** [comment]
Oh, sorry, I was a bit busy.

So if you need pagination use `useInfiniteQuery` or if you need only a page, just utilize the `queryKey`

```dart
final state = useState((name: "toyota", offset: 0, limit: 10));
final query = useQuery<dynamic, Exception>(
"listofmanufacturer/${state.name}-${state.offset}-${state.limit}",
() async {
return await getListOfVehicleBrand(state.offset,state.limit, state.name);
});

// somewhere else
state.value = (name: newName, limit: newLimit, offset: newOffset);
```

Or, there's another way

```dart
build(context){
  final query = useQuery<dynamic, Exception>(
  "listofmanufacturer",
  () async {
  return await getListOfVehicleBrand(0, 10, "marcedes");
  },
  refreshConfig: RefreshConfig.withDefaults(
    context,
     // make sure its false otherwise it can cause unneccessary re-builds unless your queryFn 
     // is a pure constant function or using useCallback() wih `[]`
    refreshOnQueryFnChange: false,
);

// Some where else
query.updateQueryFn(() async {
  return await getListOfVehicleBrand(10, 10, "marcedes");
})
query.refresh();
```

I prefer the option 1 as it'll create a separate query for each offset and limit isolating other pages. Using the 2nd way, you'll always lose the old page's info

**Comment by ganeshh123** [comment]
Is there any way we can implement this with a QueryJob? We can't use the "params" as part of the query key.

**Comment by KRTirtho** [comment]
You can utilize  [dynamic jobs keys](https://fl-query.krtirtho.dev/docs/advanced/JobsAPI#dynamic-jobs) and `args` parameter of `useQueryJob` for this

**Comment by ganeshh123** [comment]
Thanks, only a string is possible with this, right?

**Comment by KRTirtho** [comment]
Yeah, that's right. But you can pass anything using `args` which will be supplied to the `QueryJob.task` function

**Comment by KRTirtho** [comment]
Yes correct
