### ISSUE TITLE
Docs Website Down

### ISSUE THREAD

**Issue by ganeshh123** [KRTirtho/fl-query#51]
Hi,

The website that contains the docs seems to not load for me.

<img width="1246" alt="image" src="https://github.com/KRTirtho/fl-query/assets/43777439/ac69dcac-4d10-4b5d-aaa0-71772652eede">

Could you please check on this @KRTirtho

**Comment by KRTirtho** [comment]
Please recheck.

**Comment by ganeshh123** [comment]
It's back now, thank you!
